<?php

namespace Stephane\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public  function getArticles() {
		$qb = $this->createQueryBuilder('a')
					
					->leftJoin('a.image','i')
					->addSelect('i')
					
					->leftJoin('a.categories','c')
					->addSelect('c')
					
					->where('a.publication = :val')
					->setParameter('val', 1) // inutile requete preparer
					
					->orderBy('a.datecreation', 'DESC');
		
		$query = $qb->getQuery();
		return $query->getResult();
	}
	
	public  function getArticle($id) {
		$qb = $this->createQueryBuilder('a')
					
					->leftJoin('a.image','i')
					->addSelect('i')
					
					->leftJoin('a.categories','c')
					->addSelect('c')
					
					->leftJoin('a.commentaires','o')
					->addSelect('o')
					
					->where('a.publication = :val')
					->setParameter('val', 1) // inutile requete preparer
					
					->andWhere('a.id = :id')
					->setParameter('id', $id)
					->orderBy('a.datecreation', 'DESC')
					->addOrderBy('o.date', 'DESC');
					
		$query = $qb->getQuery();
		return $query->getOneOrNullResult();
	}
}
